# Generated by Django 6.0 on 2025-12-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='food',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='food',
            name='is_available',
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
