"""
Django settings for pikaquick project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-t73s^iv2#$i#48h28p43hma0!*7pd9_ftx1#b_*9)3df$sv(k%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django_bootstrap5",       # for Bootstrap
    "accounts",
    "foods",
    "payments",
    "dashboard",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pikaquick.urls'

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = 'food_ordering'  # Redirect to food ordering page after login
LOGOUT_REDIRECT_URL = 'landing_page'  # Redirect to landing page after logout

# Context Processors (Add this to TEMPLATES)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'foods.context_processors.cart_count',  # Add cart count to all templates
            ],
        },
    },
]

WSGI_APPLICATION = 'pikaquick.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'



# M-Pesa Daraja Configuration
MPESA_ENVIRONMENT = 'sandbox'  # Change to 'production' when going live
MPESA_CONSUMER_KEY = 'S9A4XejDcAtJzY4ILKjw9psmtoGUA4MtdooLCOZAWUdmCaYE'  # Get from daraja
MPESA_CONSUMER_SECRET = 'i9hbIyUk1z3iyezNrwxm4XRYMCsl4xseMRyBLDvyMclvi7gEsfYvvjs4jfBmTPRb'  # Get from daraja
MPESA_SHORTCODE = '174379'  # Sandbox shortcode
MPESA_PASSKEY = 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919'  # Sandbox passkey
MPESA_CALLBACK_URL = 'https://giggly-hank-hypermodestly.ngrok-free.dev/payments/callback/'

# M-Pesa API URLs
MPESA_SANDBOX_BASE_URL = 'https://sandbox.safaricom.co.ke'
MPESA_PRODUCTION_BASE_URL = 'https://api.safaricom.co.ke'